name: Deploy to Vercel

on:
  push:
    branches:
      - main # or specify your main branch name here

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} # Set up a secret for your Vercel token
        run: vercel --prod --token $VERCEL_TOKEN
